export const DATA = {
  es: {
    hook: [
      "Una carta anónima cita al grupo a medianoche con una promesa: oro… y una verdad incómoda.",
      "Un PNJ querido desaparece y deja solo una llave oxidada y un mapa roto.",
      "Una tormenta antinatural encierra el pueblo: nadie puede salir hasta que “se pague la deuda”.",
      "El grupo hereda una propiedad maldita que solo puede venderse si se limpia de ‘presencias’.",
      "Un culto ofrece una recompensa por recuperar un objeto antes del amanecer.",
      "Una caravana llega sin conductores, con las ruedas aún girando y sangre fresca en la lona.",
      "Se abre una grieta planar y cosas imposibles empiezan a filtrarse como humo.",
      "Un noble contrata al grupo para una misión ‘simple’… y omite un detalle letal.",
      "Una feria ambulante llega, y al día siguiente falta media aldea.",
      "Un juramento antiguo se rompe y la tierra exige un precio inmediato."
    ],
    objective: [
  "Derrotar a un caudillo de guerra que está unificando grupos de mercenarios bajo un estandarte sangriento.",
  "Romper el asedio de una fortaleza antes de que sus defensores sean masacrados.",
  "Destruir a una misteriosa criatura que lidera una horda y cuya muerte podría dispersarla.",
  "Cazar a un monstruo que ha convertido las rutas comerciales en un cementerio.",
  "Neutralizar a un señor de la guerra que ha declarado su independencia mediante conquista armada.",
  "Acabar con una guardia de élite que protege a un tirano inaccesible para que este pueda ser juzgado por la ley.",
  "Resistir y rechazar un ataque masivo hasta que lleguen refuerzos aliados.",
  "Impedir que un ejército fanático complete una purga violenta contra la población civil.",
  "Destruir una máquina de guerra viviente antes de que arrase una población indefensa.",
  "Derrotar a un estratega brillante cuya caída podría desmoronar toda la ofensiva enemiga.",

  "Interrumpir un ritual nigromántico antes de que un antiguo señor de la muerte sea devuelto al mundo.",
  "Impedir que un cambion complete un pacto infernal que le otorgaría dominio sobre la región.",
  "Desbaratar un sacrificio arcano destinado a abrir un portal permanente al Averno.",
  "Robar o destruir el foco mágico que mantiene activo un ritual de invocación demoníaca.",
  "Evitar que un círculo de magos corrompidos lleven a cabo su ritual impuro, pues les podría conceder poder o asolar una región.",
  "Romper un ritual de posesión antes de que una entidad extraplanar tome control de un gobernante.",
  "Detener una ceremonia prohibida que está drenando la vida de la población cercana para alimentar a una entidad desconocida.",
  "Neutralizar un altar arcano que amplifica un hechizo capaz de reescribir la memoria colectiva de una ciudad.",
  "Interferir en un ritual fallido cuyos efectos están desestabilizando la realidad a su alrededor.",
  "Sellar un grimorio viviente que está guiando a su portador hacia la culminación de un oscuro ritual profetizado.",

  "Rescatar a un clérigo atrapado en el Plano Sombrío antes de que su cuerpo y mente se desvanezcan para siempre.",
  "Recuperar un artefacto perdido en el Plano Elemental del Fuego/Agua antes de que provoque un desequilibrio catastrófico.",
  "Cerrar una grieta planar que está permitiendo que criaturas extraplanares crucen al mundo material.",
  "Evitar el colapso de un enclave arcano atrapado entre dos planos en colisión.",
  "Viajar al Shadowfell para recuperar el fragmento de alma de un héroe caído.",
  "Recuperar el cuerpo astral de un archimago cuyo espíritu vaga perdido entre corrientes psíquicas del Plano Astral.",
  "Restaurar los sellos que separan el mundo material del Reino Feérico antes de que ambos comiencen a fusionarse.",
  "Escoltar a una entidad exiliada de regreso a su plano de origen antes de que su presencia desestabilice la realidad.",
  "Destruir un ancla dimensional que mantiene abierto un portal inestable hacia un plano hostil.",
  "Explorar una fortaleza que existe simultáneamente en dos planos y cuyo desgarro amenaza con expandirse.",

  "Derrotar a un liche que ha iniciado un ritual que, en tres días, hará que una lluvia de meteoritos arrase el mundo.",
  "Escapar de una pirámide negra antes de que sus muros se sellen para siempre dentro de exactamente 24 horas.",
  "Robar un artefacto sagrado antes de que amanezca y se activen todas las defensas del templo.",
  "Resistir el asalto de un ejército enemigo mientras se protege una aldea hasta la llegada de refuerzos aliados al alba.",
  "Interrumpir una invocación antes de que el eclipse alcance su punto máximo y el portal se estabilice.",
  "Liberar a un prisionero condenado a ejecución antes de que la hoja del verdugo acabe con él al amanecer.",
  "Sellar una grieta elemental antes de que la marea de fuego consuma una ciudad.",
  "Desactivar una serie de sellos arcanos que explotarán simultáneamente a medianoche, destruyendo la ciudad.",
  "Evitar que un veneno se propague por el suministro de agua antes de que infecte a toda la población.",
  "Recorrer una mazmorra cambiante antes de que sus pasillos se reconfiguren y atrapen a todos en su interior.",

  "Investigar una serie de asesinatos rituales; los cadáveres han sido marcados con extraños símbolos.",
  "Descubrir quién robó un artefacto arcano de una cámara sellada sin dejar rastro alguno.",
  "Desenmascarar a un consejero real que podría estar siendo manipulado por fuerzas invisibles.",
  "Determinar el origen de una plaga que parece propagarse solo entre determinadas familias influyentes.",
  "Resolver la desaparición de varios magos cuyos laboratorios muestran señales de una lucha arcana.",
  "Descubrir qué entidad se esconde tras las visiones proféticas que están llevando a la población al pánico.",
  "Investigar un asesinato imposible ocurrido en una habitación completamente cerrada por medios mágicos.",
  "Identificar al espía que está filtrando información estratégica al enemigo desde dentro de la ciudad.",
  "Descubrir qué está provocando que los muertos regresen a la vida.",
  "Rastrear el origen y el paradero de una reliquia maldita que pasa de mano en mano y provoca comportamientos violentos en sus portadores.",

  "Negociar un tratado de paz entre dos reinos al borde de la guerra abierta.",
  "Evitar que un acuerdo diplomático fracase debido a sabotajes internos.",
  "Descubrir quién está chantajeando a un miembro clave del consejo real para manipular decisiones políticas.",
  "Evitar que la lectura de un testamento real desencadene una guerra civil entre casas nobles rivales.",
  "Mediar en un conflicto entre una ciudad humana y una comunidad no humana antes de que estalle la violencia.",
  "Desmantelar una conspiración destinada a provocar un golpe de estado silencioso.",
  "Proteger a un embajador durante una cumbre crucial donde cualquier incidente podría desencadenar una guerra.",
  "Convencer a una poderosa casa noble de retirar su apoyo a una rebelión inminente.",
  "Supervisar un juicio público cuyo veredicto podría dividir al reino en facciones irreconciliables.",
  "Impedir que una alianza estratégica se rompa tras la revelación de un secreto comprometedor.",

  "Asaltar una fortaleza inexpugnable para liberar a los prisioneros retenidos en sus mazmorras.",
  "Tomar una torre arcana fuertemente protegida antes de que su mago residente complete un experimento o ritual peligroso.",
  "Irrumpir en un campamento militar enemigo para destruir sus suministros y debilitar su ofensiva.",
  "Asaltar una cueva ocupada por criaturas monstruosas que aterrorizan la región.",
  "Romper las defensas de una prisión de alta seguridad para rescatar a un aliado capturado.",
  "Conquistar una muralla estratégica que impide el avance del ejército aliado.",
  "Lanzar un asalto naval contra una flota pirata atracada en un puerto oculto.",
  "Tomar un templo fortificado que ha sido convertido en base de operaciones por un culto armado.",
  "Conseguir fugarse de una prisión.",
  "Asaltar un bastión infernal surgido repentinamente en el corazón de una ciudad.",

  "Infiltrarse en la mansión de un noble corrupto para robar documentos que prueban su traición.",
  "Sustraer una reliquia sagrada de un templo sin activar sus defensas mágicas.",
  "Suplantar la identidad de un emisario extranjero para acceder a información clasificada.",
  "Robar un artefacto arcano durante una gala multitudinaria sin que nadie advierta su desaparición.",
  "Infiltrarse en un archivo secreto custodiado por constructos mágicos para copiar información prohibida.",
  "Intercambiar un objeto maldito por una réplica idéntica sin que su actual portador lo descubra.",
  "Acceder a una bóveda subterránea cuya entrada solo aparece durante unos minutos cada noche.",
  "Infiltrarse en una orden o secta clandestina haciéndose pasar por un nuevo iniciado.",
  "Recuperar un objeto confiscado del almacén de pruebas del consejo sin dejar evidencia alguna.",
  "Extraer a un informante de una ciudad enemiga sin que se active ninguna alarma.",

  "Reunir los fragmentos dispersos de una arma legendaria capaz de derrotar a una antigua amenaza que regresa.",
  "Despertar a un dragón ancestral para que cumpla un juramento olvidado y defienda el reino.",
  "Recuperar la corona perdida de un linaje sagrado cuyo portador puede unificar las tierras divididas.",
  "Cerrar una brecha colosal en el firmamento por la que descienden criaturas celestiales y abisales.",
  "Adentrarse en la tumba de un dios caído para impedir que su esencia corrupta renazca como una entidad devoradora de mundos.",
  "Impedir que se realice un ritual que abriría un portal a los Reinos Lejanos; lo que provocaría el fin de civilizaciones enteras y puede que del propio mundo.",
  "Derrotar a un dragón ancestral que ha proclamado su dominio sobre varios reinos y exige tributo bajo amenaza de aniquilación.",
  "Destruir un artefacto forjado al inicio de los tiempos antes de que caiga en manos equivocadas o se utilice para hacer el mal.",
  "Guiar a un ejército unido bajo un único estandarte para enfrentar una invasión de proporciones míticas.",
  "Romper una profecía ancestral destinada a condenar al mundo a una era de oscuridad eterna.",

  "Descubrir qué maldición pesa sobre una familia noble cuyos miembros mueren uno a uno en circunstancias inquietantes.",
  "Explorar un castillo abandonado donde cada noche se escuchan lamentos provenientes de sus muros.",
  "Romper el vínculo que ata a un vampiro ancestral a la sangre de un linaje condenado.",
  "Investigar por qué los habitantes de un pueblo han comenzado a comportarse como si compartieran una misma voluntad.",
  "Liberar el espíritu de una mujer acusada de brujería cuya ejecución provocó una maldición sobre la región.",
  "Descubrir quién —o qué— ocupa realmente el trono de un señor que jamás abandona sus aposentos.",
  "Impedir que una antigua campana funeraria vuelva a sonar, pues cada toque anuncia una muerte inevitable.",
  "Sobrevivir a una noche en una mansión donde los espejos muestran escenas del futuro que inevitablemente se cumplen.",
  "Investigar una abadía aislada cuyos clérigos aseguran custodiar algo que nunca debe ser visto.",
  "Desentrañar el secreto de un cementerio donde las tumbas aparecen abiertas cada amanecer.",

  "Descubrir qué entidad ancestral se comunica con los habitantes a través de sueños compartidos que están erosionando su cordura.",
  "Cerrar una brecha invisible por la que algo observa el mundo y altera sutilmente la realidad a su alrededor.",
  "Impedir que se complete la invocación de un ser que alteraría la realidad para siempre.",
  "Explorar una ciudad sumergida que reaparece cada cierto ciclo lunar trayendo consigo ecos de otra era.",
  "Destruir un artefacto cuya mera proximidad provoca visiones de futuros imposibles y realidades alternativas.",
  "Investigar la aparición de extrañas criaturas cuya presencia distorsiona la realidad.",
  "Evitar que una estrella desconocida alineada en el firmamento abra un canal hacia una conciencia cósmica.",
  "Sellar un pozo sin fondo del que emergen susurros capaces de alterar la voluntad de quien los escucha.",
  "Investigar por qué ciertos lugares de la ciudad parecen reconfigurarse y cambiar cuando nadie los está mirando.",
  "Impedir que una antigua ciudadela vuelva a emerger desde las profundidades del océano.",

  "Escoltar a una joven heredera cuya vida corre peligro hasta un lugar donde pueda reclamar su derecho legítimo.",
  "Proteger a un archimago mientras completa un ritual que lo deja completamente indefenso.",
  "Custodiar una reliquia sagrada durante su traslado a través de territorios hostiles.",
  "Defender una aldea aislada de ataques nocturnos hasta que llegue ayuda exterior.",
  "Escoltar a un emisario que porta información crucial para evitar una guerra inminente.",
  "Proteger a un testigo clave cuyo testimonio podría desmantelar una conspiración de alto nivel.",
  "Garantizar la seguridad de una caravana que transporta un artefacto extremadamente peligroso.",
  "Mantener con vida a un sacerdote que es el único capaz de contener una maldición creciente.",
  "Proteger a un enemigo que posee información vital mientras múltiples facciones intentan asesinarlo o liberarlo.",
  "Proteger a una criatura recién nacida cuyo destino está ligado a una antigua profecía.",

  "Reforzar los sellos que mantienen encerrada a una entidad ancestral.",
  "Reactivar un círculo de contención olvidado que mantenía atrapada una anomalía arcana.",
  "Cerrar una grieta planar.",
  "Sellar una tumba profanada antes de que lo que duerme en su interior despierte por completo.",
  "Restaurar una prisión arcana cuya integridad se está debilitando peligrosamente.",
  "Encerrar nuevamente a un demonio que ha logrado liberarse parcialmente de su confinamiento.",
  "Neutralizar un artefacto que irradia energía corruptora y altera el entorno cercano.",
  "Evitar que una grieta dimensional continúe creciendo y fracturando la realidad.",
  "Reforzar el sello que mantiene cerrado un portal a otro plano antes de que se abra.",
  "Contener a una criatura antes de que rompa sus ataduras.",

  "Sobrevivir a una travesía por un desierto maldito donde el agua se evapora de los recipientes durante la noche.",
  "Atravesar una tundra azotada por tormentas arcanas mientras algo acecha bajo el hielo.",
  "Escapar de una jungla viva cuyos senderos cambian y donde la propia vegetación parece hostil.",
  "Resistir varios días dentro de una ciudad en ruinas infestada de criaturas mientras se agotan los suministros.",
  "Atravesar una cordillera inestable tras un derrumbe que ha bloqueado la única ruta conocida.",
  "Sobrevivir en una isla aislada después de un naufragio mientras algo observa desde el interior de la selva.",
  "Defender un refugio improvisado mientras una oscuridad mágica cubre el territorio y criaturas desconocidas merodean en ella.",
  "Encontrar refugio antes de que una tormenta elemental arrase todo a su paso.",
  "Escapar de un territorio controlado por vampiros.",
  "Mantener con vida al grupo mientras una maldición desconocida debilita progresivamente a sus miembros.",

  "Detener el avance de un tarrasque cuyo despertar ha comenzado a devastar ciudades enteras.",
  "Derrotar a un dragón antiguo que ha establecido su guarida sobre una capital conquistada.",
  "Destruir el filacteria de un liche ancestral para impedir su regreso eterno.",
  "Cazar a un leviatán colosal que emerge del océano cada década para arrasar las costas.",
  "Enfrentarse a un titán encadenado cuya liberación provocaría cataclismos naturales.",
  "Derrotar a un fénix corrompido cuya resurrección perpetua alimenta una tormenta de fuego interminable.",
  "Acabar con un señor vampírico que gobierna una ciudad en secreto desde generaciones atrás.",
  "Derrotar a una hidra mítica cuyas cabezas regeneradas adquieren nuevas habilidades con cada corte.",
  "Impedir que una saga consiga hacerse con un niño.",
  "Enfrentarse a una bestia ancestral proclamada como avatar viviente de un dios olvidado.",

  "Descubrir quién ha sido reemplazado por un doppelganger mientras investigáis el robo de una reliquia que estabais custodiando.",
  "Descubrir quién del grupo ha hecho un pacto secreto cuyo pago son las almas del resto.",
  "Descubrir quién está manipulando vuestros recuerdos tras una misión de la que ninguno conserva una versión coherente.",
  "Identificar al infiltrado del grupo que os está guiando hacia una trampa cuidadosamente diseñada.",
  "Desentrañar con quién del grupo se comunica una entidad misteriosa en sueños y altera sus decisiones.",
  "Descubrir si uno del grupo fue reemplazado hace tiempo y lleva semanas manipulando al grupo.",
  "Descubrir si alguien, o todos los del grupo, son versiones alteradas de quienes creen ser y qué ocurrió realmente con los originales.",
  "Descubrir quién del grupo oculta una reliquia que está alterando las decisiones del grupo y cómo destruirla.",
  "Descubrir quién del grupo está sembrando pruebas falsas para enfrentaros entre vosotros.",
  "Determinar si una amenaza externa es real o si todo forma parte de una manipulación diseñada para dividir al grupo."
],
    location: [
      "Una cripta inundada bajo una capilla en ruinas.",
      "Un bosque olvidado donde los árboles susurran nombres reales.",
      "Un faro costero apagado, golpeado por olas negras.",
      "Un teatro abandonado con telones que se mueven solos.",
      "Una mina colapsada que aún emite cantos metálicos.",
      "Un puente antiguo custodiado por estatuas que parpadean.",
      "Una taberna de carretera donde nadie recuerda haber entrado.",
      "Un laboratorio arcano enterrado bajo una granja.",
      "Una fortaleza en un acantilado con pasillos imposibles.",
      "Un mercado nocturno feérico que solo existe hasta el alba."
    ],
    opposition: [
      "Un nigromante menor con guardias no-muertos improvisados.",
      "Una banda de bandidos con información que no deberían tener.",
      "Un demonio atado a un sello, intentando convencer al grupo.",
      "Un cambiante infiltrado que provoca desconfianza y errores.",
      "Bestias corrompidas que protegen un corazón oscuro.",
      "Un caballero maldito que no puede morir… pero sí detenerse.",
      "Un culto organizado con un líder carismático y fanáticos.",
      "Un enjambre de sombras que apaga luz y esperanza.",
      "Un espíritu vengativo ligado al lugar y a una promesa rota.",
      "Una criatura de otro plano que aprende rápido y copia tácticas."
    ]
  },

  en: {
    hook: [
      "An anonymous letter summons the party at midnight with a promise: gold… and an uncomfortable truth.",
      "A beloved NPC vanishes, leaving only a rusty key and a torn map.",
      "An unnatural storm locks the town in: no one can leave until “the debt” is paid.",
      "The party inherits a cursed property that can only be sold once it’s cleared.",
      "A cult offers a reward to retrieve an object before dawn.",
      "A caravan arrives without drivers, wheels still spinning, blood fresh on the canvas.",
      "A planar crack opens and impossible things seep through like smoke.",
      "A noble hires the party for a ‘simple’ job… and omits a lethal detail.",
      "A traveling fair arrives, and by morning half the village is missing.",
      "An ancient vow breaks and the land demands immediate payment."
    ],
    objective: [
      "Rescue a missing person before the ritual finishes.",
      "Recover a stolen artifact and return it to its shrine.",
      "Disrupt a summoning that is weakening the planar veil.",
      "Escort a key witness to a safe location.",
      "Destroy a corruption source poisoning the woods.",
      "Free prisoners from a makeshift stronghold.",
      "Seal a magical rift before it becomes a stable portal.",
      "Steal a forbidden book without alerting its keepers.",
      "Negotiate a truce between two factions before war ignites.",
      "Survive and escape a sealed place before it ‘activates’."
    ],
    location: [
      "A flooded crypt beneath a ruined chapel.",
      "A forgotten forest where trees whisper true names.",
      "A darkened coastal lighthouse battered by black waves.",
      "An abandoned theater with curtains that move on their own.",
      "A collapsed mine still singing with metallic echoes.",
      "An ancient bridge watched by statues that blink.",
      "A roadside inn where no one remembers entering.",
      "An arcane lab buried beneath a farmhouse.",
      "A cliffside fortress with impossible corridors.",
      "A fey night market that exists only until sunrise."
    ],
    opposition: [
      "A minor necromancer with improvised undead guards.",
      "A bandit crew with information they shouldn’t have.",
      "A demon bound to a seal, trying to bargain with the party.",
      "A shapeshifter infiltrator sowing distrust and mistakes.",
      "Corrupted beasts protecting a dark heart.",
      "A cursed knight who can’t die… but can be stopped.",
      "An organized cult with a charismatic leader and zealots.",
      "A swarm of shadows that snuffs out light and resolve.",
      "A vengeful spirit tied to the place and a broken promise.",
      "An outsider creature that learns fast and copies tactics."
    ]
  }
};

export const SECTIONS = [
  { key: "hook", label_es: "Gancho",   label_en: "Hook" },
  { key: "objective", label_es: "Objetivo", label_en: "Objective" },
  { key: "location", label_es: "Lugar", label_en: "Location" },
  { key: "opposition", label_es: "Oposición", label_en: "Opposition" }
];
